// <auto-generated />
using System;
using IceCity.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IceCity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260223141700_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IceCity.Domain.Models.Heater", b =>
                {
                    b.Property<int>("HeaterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HeaterId"));

                    b.Property<string>("HeaterType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<double>("PowerValue")
                        .HasColumnType("float");

                    b.HasKey("HeaterId");

                    b.HasIndex("HouseId");

                    b.ToTable("Heaters");
                });

            modelBuilder.Entity("IceCity.Domain.Models.House", b =>
                {
                    b.Property<int>("HouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("HouseId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("IceCity.Domain.Models.MonthlyCostReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HouseId")
                        .HasColumnType("int");

                    b.Property<double>("MedianHeaterValue")
                        .HasColumnType("float");

                    b.Property<double>("MonthlyAverageCost")
                        .HasColumnType("float");

                    b.Property<int>("ReportMonth")
                        .HasColumnType("int");

                    b.Property<double>("TotalWorkingHours")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("HouseId");

                    b.ToTable("MonthlyCostReports");
                });

            modelBuilder.Entity("IceCity.Domain.Models.Owner", b =>
                {
                    b.Property<int>("OwnerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OwnerId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerId");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("IceCity.Domain.Models.SensorReading", b =>
                {
                    b.Property<int>("SensorReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SensorReadingId"));

                    b.Property<int>("HeaterId")
                        .HasColumnType("int");

                    b.Property<double>("HeaterValue")
                        .HasColumnType("float");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("WorkingHours")
                        .HasColumnType("float");

                    b.HasKey("SensorReadingId");

                    b.HasIndex("HeaterId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("IceCity.Domain.Models.Heater", b =>
                {
                    b.HasOne("IceCity.Domain.Models.House", "House")
                        .WithMany("Heaters")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IceCity.Domain.Models.House", b =>
                {
                    b.HasOne("IceCity.Domain.Models.Owner", "Owner")
                        .WithMany("Houses")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("IceCity.Domain.Models.MonthlyCostReport", b =>
                {
                    b.HasOne("IceCity.Domain.Models.House", "House")
                        .WithMany("MonthlyCostReports")
                        .HasForeignKey("HouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("House");
                });

            modelBuilder.Entity("IceCity.Domain.Models.SensorReading", b =>
                {
                    b.HasOne("IceCity.Domain.Models.Heater", "Heater")
                        .WithMany("SensorReadings")
                        .HasForeignKey("HeaterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Heater");
                });

            modelBuilder.Entity("IceCity.Domain.Models.Heater", b =>
                {
                    b.Navigation("SensorReadings");
                });

            modelBuilder.Entity("IceCity.Domain.Models.House", b =>
                {
                    b.Navigation("Heaters");

                    b.Navigation("MonthlyCostReports");
                });

            modelBuilder.Entity("IceCity.Domain.Models.Owner", b =>
                {
                    b.Navigation("Houses");
                });
#pragma warning restore 612, 618
        }
    }
}
